### ISSUE TITLE
Question regarding video conference output (voice from other attendees)

### ISSUE THREAD

**Issue by tethragon** [toadjaune/pulseaudio-config#11]
I think that using your script, voice from video conference attendees will output to speakers and then return through the virtual2 mic back to them, essentially creating an infinite loop. Is there any way around that?

**Comment by toadjaune** [comment]
In my experience using this script (which, admittedly, is quite old), that wasn't the case.

Have you looked at the schema, at the bottom of README ?
The videoconference output is not managed by this script, and doesn't need to be sent through any virtual device, just directly to your speakers. Is that how you set it up ?

If people in the videoconference can hear themselves, have you considered that maybe you're having "normal" echo ? Like, your speakers physically sending sound to your microphone. Maybe try with headphones, or mute your microphone, to rule this out ?

**Comment by tethragon** [comment]
I am using headset, so there is no sound from speakers going physically to my microphone.

Maybe I am setting inputs/outputs wrong. I'll do some more testing.

Thanks for the answer.

**Comment by toadjaune** [comment]
Sure !
Feel free to re-open if needed :)
